### ISSUE TITLE
Cityscape dataset

### ISSUE THREAD

**Issue by JoeFang123** [haofeixu/rdn4depth#1]
I wonder how to download the Cityscape dataset from https://www.cityscapes-dataset.com, I have registered but didn't have the access to the leftImg8bit_sequence_trainvaltest.zip.

**Comment by haofeixu** [comment]
Hi @JoeFang123 , you need to email to the cityscapes team for requesting the `leftImg8bit_sequence_trainvaltest.zip`, when you receive reply, you will have access to the corresponding data via [the download page](https://www.cityscapes-dataset.com/downloads/). Hope it helps.
