### ISSUE TITLE
What does "depth" mean?

### ISSUE THREAD

**Issue by MoriYu0011** [haofeixu/rdn4depth#3]
I want to know about “depth” in your paper.
* depth is z of 3D(x,y,z) coordination?
* depth of .npy file(inference.py) is metric?

Thank you.

**Comment by haofeixu** [comment]
Hi @MoriYu0011 ,

Thanks for your interest. Yes, depth is `z` coordinate of a 3D point. However, the depth produced by our method is a relative metric as we are in a monocular setting, and we use ground truth depth to get the correct scale. You can refer to the code [here](https://github.com/haofeixu/rdn4depth/blob/64432608c896cc022079a4a6b167cde228823006/evaluate.py#L78-L80).

**Comment by MoriYu0011** [comment]
Thanks so much!

**Comment by MoriYu0011** [comment]
Finally, `pred_depth` cannot be converted to metric without any ToF sensors?
It seems 
* We need at least one ToF sensor when we take video data, and
* `rdn4depth` is only useful for increasing  resolution of the ToF data.

Just to confirm, @haofeixu

**Comment by haofeixu** [comment]
No metric scale may be a limitation of the monocular methods, but the actual scale may be potentially recovered by leveraging additional senor or priors (for example, object size).

**Comment by MoriYu0011** [comment]
Noted with thanks.
